[pytest]
minversion = 7.0
addopts = -p no:playwright
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke tests
    contract: contract tests
    regression: regression test
    ui: UI tests powered by Playwright
    external: tests that require live external services or internet access
    positive: positive tests
    negative: negative tests
    vacancy: tests for /vacancies/{vacancy_id}
    vacancies: tests for /vacancy
